### ISSUE TITLE
Title page authors don't match acknowledged contributes in preamble

### ISSUE THREAD

**Issue by jjscheel** [riscv/riscv-smcdeleg#3]
Greg Favor and John Hauser are missing from the title page.  Please reconcile.

**Comment by bcstrongx** [comment]
Looking at ratified specs, I don't see a single one that has all contributors on the title page.  Greg and John contributed in the form of feedback during the ARC review process, but the original draft was written by me, Atish, and Allen.  So I'd recommend leaving as-is, or perhaps removing authors from the title page altogether (which several specs do).

**Comment by jjscheel** [comment]
My recommendation would be the latter.  Otherwise, we run the risk of confusion...

**Comment by jjscheel** [comment]
Normally, I'd say you could point to the whole TG, but given it's Fast Track, probably best to simply leave it off.
